alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.wishlist enable row level security;
drop policy if exists "anon_all_products" on public.products;
create policy "anon_all_products" on public.products for all to anon using (true) with check (true);
drop policy if exists "anon_all_users" on public.users;
create policy "anon_all_users" on public.users for all to anon using (true) with check (true);
drop policy if exists "anon_all_sessions" on public.sessions;
create policy "anon_all_sessions" on public.sessions for all to anon using (true) with check (true);
drop policy if exists "anon_all_cart" on public.cart_items;
create policy "anon_all_cart" on public.cart_items for all to anon using (true) with check (true);
drop policy if exists "anon_all_orders" on public.orders;
create policy "anon_all_orders" on public.orders for all to anon using (true) with check (true);
drop policy if exists "anon_all_order_items" on public.order_items;
create policy "anon_all_order_items" on public.order_items for all to anon using (true) with check (true);
drop policy if exists "anon_all_wishlist" on public.wishlist;
create policy "anon_all_wishlist" on public.wishlist for all to anon using (true) with check (true);
grant usage on schema public to anon;
grant select, insert, update, delete on all tables in schema public to anon;
grant usage on all sequences in schema public to anon;
