-- Maison Velour — Postgres schema for Supabase
-- Run by scripts/seed.js (which connects with the database connection string).
-- Safe to re-run: every statement is idempotent.

create table if not exists products (
  id      integer generated by default as identity primary key,
  name    text not null,
  cat     text not null,
  price   numeric(10,2) not null default 0,
  was     numeric(10,2) not null default 0,
  art1    text not null default '#ffffff',
  art2    text not null default '#000000',
  glyph   text not null default '✦',
  badge   text not null default '',
  image   text not null default ''
);

create table if not exists users (
  id         integer generated by default as identity primary key,
  name       text not null,
  email      text unique not null,
  pass       text not null,
  phone      text not null default '',
  is_admin   integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists sessions (
  token      text primary key,
  user_id    integer not null references users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists cart_items (
  id            integer generated by default as identity primary key,
  session_token text not null,
  product_id    integer not null references products(id) on delete cascade,
  qty           integer not null default 1
);

create table if not exists orders (
  id             integer generated by default as identity primary key,
  num            text unique not null,
  user_id        integer references users(id) on delete set null,
  email          text not null,
  total          numeric(10,2) not null default 0,
  items          integer not null default 0,
  status         text not null default 'In transit 🚚',
  ship_name      text not null default '',
  ship_phone     text not null default '',
  ship_address   text not null default '',
  ship_city      text not null default '',
  ship_country   text not null default '',
  ship_zip       text not null default '',
  payment_method text not null default '',
  payment_status text not null default 'unpaid',
  payment_ref    text not null default '',
  created_at     timestamptz not null default now()
);

create table if not exists order_items (
  id         integer generated by default as identity primary key,
  order_id   integer not null references orders(id) on delete cascade,
  product_id integer not null,
  name       text not null,
  price      numeric(10,2) not null default 0,
  qty        integer not null default 1
);

-- ---- Repair columns on databases that predate them -------------------------
-- `create table if not exists` above does nothing when the table already
-- exists, so a restored backup or an older database keeps its old columns and
-- the API then fails with "Could not find the 'payment_method' column".
-- These statements are what actually migrate such a database forward.
alter table orders add column if not exists ship_zip       text not null default '';
alter table orders add column if not exists payment_method text not null default '';
alter table orders add column if not exists payment_status text not null default 'unpaid';
alter table orders add column if not exists payment_ref    text not null default '';

-- session_token and user_id are both nullable: an entry belongs to either an
-- anonymous session or a logged-in account, never both.
create table if not exists wishlist (
  id            integer generated by default as identity primary key,
  session_token text,
  user_id       integer references users(id) on delete cascade,
  product_id    integer not null references products(id) on delete cascade
);

create index if not exists cart_items_session_idx on cart_items(session_token);
create index if not exists orders_email_idx        on orders(email);
create index if not exists orders_num_idx          on orders(num);
create index if not exists wishlist_session_idx    on wishlist(session_token);
create index if not exists wishlist_user_idx       on wishlist(user_id);

create unique index if not exists cart_items_session_product_uniq
  on cart_items(session_token, product_id);
create unique index if not exists wishlist_session_product_uniq
  on wishlist(session_token, product_id) where session_token is not null;
create unique index if not exists wishlist_user_product_uniq
  on wishlist(user_id, product_id) where user_id is not null;

-- ---- Access control -------------------------------------------------------
-- The API is the only thing that talks to this database. It does so with the
-- service_role key, which bypasses Row Level Security by design. Enabling RLS
-- with no policies therefore means the public anon key cannot read or write
-- anything directly — the storefront and admin panel must go through /api.
alter table products    enable row level security;
alter table users       enable row level security;
alter table sessions    enable row level security;
alter table cart_items  enable row level security;
alter table orders      enable row level security;
alter table order_items enable row level security;
alter table wishlist    enable row level security;

-- ---- Remove stray permissive policies -------------------------------------
-- `enable row level security` above does NOT remove policies that already
-- exist, so anything an earlier version created survives every re-seed. That
-- happened here: a since-deleted `rls-fix.sql` added `anon_all_*` policies, and
-- the dashboard had `allow read users`, `allow all sessions` and friends — all
-- granting the public anon key full access to every table, passwords included.
-- This app is reached only through the API, which uses the service_role key and
-- bypasses RLS, so no policy should target `anon` or `public` at all. Policies
-- for other roles (e.g. `authenticated`) are left alone.
do $$
declare r record;
begin
  for r in
    select tablename, policyname
      from pg_policies
     where schemaname = 'public'
       and roles && '{anon,public}'::name[]
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;
